# Generated by Django 3.0.5 on 2020-04-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.BigIntegerField()),
            ],
        ),
    ]
