# Generated by Django 3.0.5 on 2020-04-04 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='time',
            field=models.TimeField(default=datetime.time(18, 38, 22, 782875)),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 18, 38, 22, 782875)),
        ),
    ]
