# Generated by Django 3.0.5 on 2020-04-04 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200404_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.TimeField(default=datetime.time(18, 44, 11, 321602)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.TextField(default=datetime.datetime(2020, 4, 4, 18, 44, 11, 321602)),
        ),
    ]
