# Generated by Django 3.0.5 on 2020-04-05 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200404_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 5)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.TimeField(default=datetime.time(7, 42, 42, 419215)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.TextField(default=datetime.datetime(2020, 4, 5, 7, 42, 42, 419215)),
        ),
    ]
