# Generated by Django 3.0.5 on 2020-04-05 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200405_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.TextField(default=datetime.date(2020, 4, 5)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.TextField(default=datetime.time(8, 38, 3, 180746)),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='timestamp',
            field=models.TextField(default=datetime.datetime(2020, 4, 5, 8, 38, 3, 180746)),
        ),
    ]
